import { Providers } from '../Provider';
import './global.css';
import './styles.css';
// import './antDesignStyles.less';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
